targets:
  $default:
    builders:
      ferry_generator|graphql_builder:
        enabled: true
        options:
          schema: test_drive|lib/graphql/schema.docs.graphql
      ferry_generator|serializer_builder:
        enabled: true
        options:
          schema: test_drive|lib/graphql/schema.docs.graphql